name: Build and Upload Development

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install 

    - name: Build project
      run: npm run build:dev

    - name: Create .zip of dist directory
      run: zip -r dist.zip dist 

    - name: Get total number of releases
      id: get_release_count
      uses: actions/github-script@v6
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const totalReleases = releases.data.length + 1;
          console.log(`Total releases: ${totalReleases}`);
          core.setOutput('totalReleases', totalReleases);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current version
      id: current_version
      run: echo "TAG=build_dev_$(date +'%Y-%m-%d')_v${{ steps.get_release_count.outputs.totalReleases }}" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git tag $TAG 
        git push origin $TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload dist.zip to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip
        tag_name: ${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up email subject
      id: email_subject
      run: echo "EMAIL_SUBJECT=Dist.zip for ${{ env.TAG }} is ready" >> $GITHUB_ENV

    - name: Send email notification
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{ secrets.GMAIL_USERNAME }}
        password: ${{ secrets.GMAIL_APP_PASSWORD }}
        subject: ${{ env.EMAIL_SUBJECT }}
        body: |
          The dist.zip file is now available for download at the following link:
          https://github.com/${{ github.repository }}/releases/download/${{ env.TAG }}/dist.zip
        to: elvin758@gmail.com
        from: ${{ secrets.GMAIL_USERNAME }}
