name: Build and Upload #Nombre del workflow

on:
  push:
    branches:
      - main #cuando se detectan cambios se dispara el action

jobs:
  build:
    runs-on: ubuntu-latest #corremos el proyecto sobre linux

    steps:
    - name: Checkout repository #Nos movemos al repo
      uses: actions/checkout@v2 #usamos la ultima version de actions

    - name: Set up Node.js  #instalamos node
      uses: actions/setup-node@v2 #Usamos el action oficial de node 
      with:
        node-version: '16' #instalamos la ultima version

    - name: Install dependencies #instalamos todas las dependencias
      run: npm install 

    - name: Build project #Construimos el proyecto
      run: npm run build

    - name: Create .zip of dist directory 
      run: zip -r dist.zip dist #comprimimos la carpeta dist en un archivo zip

    - name: Get total number of releases #con este paso obtenemos el total releases y le sumamos +1 para que los tag se diferencien haciendo alusión a versiones
      id: get_release_count
      uses: actions/github-script@v6
      with:
        script: |
          const releases = await github.rest.repos.listReleases({
            owner: context.repo.owner,
            repo: context.repo.repo,
          });
          const totalReleases = releases.data.length + 1;
          console.log(`Total releases: ${totalReleases}`);
          core.setOutput('totalReleases', totalReleases);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get current version #creamos una variable de entorno que haga referencia a este repo y guardamos el nombre
      id: current_version
      run: echo "TAG=build_date$(date +'%Y_%m_%d')_v${{ steps.get_release_count.outputs.totalReleases }}" >> $GITHUB_ENV

    - name: Create tag #creamos el tag con el nombre dado en el paso anterio
      run: |
        git tag $TAG 
        git push origin $TAG
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload dist.zip to GitHub Releases #`dist.zip` es el archivo que queremos subir
      uses: softprops/action-gh-release@v1
      with:
        files: dist.zip
        tag_name: ${{ env.TAG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
